//
// Created by Buns_ on 2026/8/23.
//

#ifndef LAYERED_EMBEDDED_C_PLATFORM_TIM_H
#define LAYERED_EMBEDDED_C_PLATFORM_TIM_H

typedef enum {
  PLATFORM_TIM_CHANNEL_1 = 0U,
  PLATFORM_TIM_CHANNEL_2,
  PLATFORM_TIM_CHANNEL_3,
  PLATFORM_TIM_CHANNEL_4,
  PLATFORM_TIM_CHANNEL_ALL,
} Platform_TIM_Channel;

typedef enum {
  PLATFORM_TIM_TIM1 = 0U,
  PLATFORM_TIM_TIM2,
  PLATFORM_TIM_TIM3,
  PLATFORM_TIM_TIM4,
} Platform_TIM_Instance;

#endif //LAYERED_EMBEDDED_C_PLATFORM_TIM_H
